routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('creausuario', function(){

	$usuario = new App\User;
	$usuario->name = "Administrador";
	$usuario->email = "administrador@correocorrecto.com";
	$usuario->password = bcrypt('admin');
	$usuario->save();

	return $usuario;

});

Route::resource('obras', 'ObrasController');

Route::get('/', ['as' => 'home', 'uses' => 'PagesController@home']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('obra/search', ['as' => 'search', 'uses' => 'ObrasController@search']);

Route::get('obra/filter', ['as' => 'obras.filter', 'uses' => 'ObrasController@filter']);

Route::get('galeria/index', ['as' => 'galeria.index', 'uses' => 'ImagenesController@index']);

Route::get('obra/quick', ['as' => 'obras.quicksearch', 'uses' => 'ObrasController@quickSearch']);

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

resources/views/home.blade.php
@extends('layout_def')

@section('contenido')

<div class="container" style="margin: 0">
	<h1>Página principal</h1>
	<h3>Aquí se insertarán de momento las instrucciones de uso de la aplicación</h3>
</div>

@stop

resources/views/layout_def.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Web del TEU</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>
        
<body>
	
	<nav style = "padding: .5em 1em" class="nav">
			<a class="navbar-brand" href="{{route('home')}}"><img src="../static_img/logo.jpg" alt="Logo del TEU" width="100" height="50"></a>
			<a class="nav-link" href="{{route('obras.filter', null)}}">Hacer una consulta</a>
			<a class="nav-link" href="{{route('galeria.index')}}">Galería de imágenes</a>
			@if(!Auth::check())
				<a class="nav-link" href="/login">Iniciar sesión <span class="sr-only">(current)</span></a>
			@else
				<a class="nav-link" href="{{route('obras.create')}}">Insertar datos <span class="sr-only">(current)</span></a>
				<a class="nav-link" href="/logout">Cerrar Sesión de {{Auth::user()->name}}</a>
			@endif
		</nav>

@yield('contenido')
</body>
<footer style="margin:0;">
	<div class="container" style="margin: 0; padding: 0; font-size: 9px">
		<img src="../static_img/ministerio.png" alt="Ministerio de Economía, Comercio y Competitividad; Secretaría de Estado de Investigación, Desarrollo e Innovación">
		<b>Proyecto de Investigación HISTORIA DEL TEATRO UNIVERSITARIO ESPAÑOL: FFI2015-66393-P</b>
	</div>
</footer>
<script src="/js/all.js"></script>
</html>