routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('creausuario', function(){

	$usuario = new App\User;
	$usuario->name = "Administrador";
	$usuario->email = "administrador@correocorrecto.com";
	$usuario->password = bcrypt('admin');
	$usuario->save();

	return $usuario;

});

Route::resource('obras', 'ObrasController');

Route::get('/', ['as' => 'home', 'uses' => 'PagesController@home']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('obra/search', ['as' => 'search', 'uses' => 'ObrasController@search']);

Route::get('obra/filter', ['as' => 'obras.filter', 'uses' => 'ObrasController@filter']);

Route::get('galeria/index', ['as' => 'galeria.index', 'uses' => 'ImagenesController@index']);

Route::get('obra/quick', ['as' => 'obras.quicksearch', 'uses' => 'ObrasController@quickSearch']);

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Obra.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Obra extends Model
{
     protected $fillable = ['id', 'titulo', 'autoria', 'genero_dramatico', 'fecha_de_estreno', 'traduccion', 'adaptacion', 'direccion', 'reparto', 'escenografia', 'figurines', 'sonido_y_musica', 'coreografia', 'otros', 'resenyas_criticas', 'bibliografia', 'material_grafico', 'comentarios', 'usr_creador', 'usr_last_mod'];

     public function foto()
     {
     	return $this->hasMany(Foto::class);
     }

     public function fichero()
     {
     	return $this->hasMany(Fichero::class);
     }
}

app/Http/Controllers/ObrasController.php
<?php

namespace App\Http\Controllers;

use Storage;

use App\Obra;

use App\Foto;

use Auth;

use App\Fichero;

use Illuminate\Http\Request;

class ObrasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('obras/c_obra');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = Obra::create($request->all())->id;
        if($request->has('img'))
        {
            foreach($request->img as $foto)
            {
                Foto::create(['obra_id'=>$id, 'ruta' => $foto->store('public/img')]);
            }
        }
        if($request->has('fich'))
        {
            foreach($request->fich as $fichero)
            {
                Fichero::create(['obra_id'=>$id,'nombre'=>pathinfo($fichero->getClientOriginalName(), PATHINFO_FILENAME), 'ruta'=>$fichero->store('public/ficheros')]);
            }
        }

        return redirect()->route('obras.show', $id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $obra = Obra::with('foto', 'fichero')->where('id', $id)->get();
        if($obra[0]->direccion != null)
            $obra[0]->direccion = explode(";", $obra[0]->direccion);
        if($obra[0]->reparto != null)
            $obra[0]->reparto = explode(";", $obra[0]->reparto);
        if($obra[0]->escenografia != null)
            $obra[0]->escenografia = explode(";", $obra[0]->escenografia);
        if($obra[0]->figurines != null)
            $obra[0]->figurines = explode(";", $obra[0]->figurines);
        if($obra[0]->sonido_y_musica != null)
            $obra[0]->sonido_y_musica = explode(";", $obra[0]->sonido_y_musica);
        if($obra[0]->coreografia != null)
            $obra[0]->coreografia = explode(";", $obra[0]->coreografia);
        if($obra[0]->otros != null)
            $obra[0]->otros = explode(";", $obra[0]->otros);
        if($obra[0]->resenyas_criticas != null)
            $obra[0]->resenyas_criticas = explode(";", $obra[0]->resenyas_criticas);
        if($obra[0]->bibliografia != null)
            $obra[0]->bibliografia = explode(";", $obra[0]->bibliografia);
        if($obra[0]->material_grafico != null)
            $obra[0]->material_grafico = explode(";", $obra[0]->material_grafico);
        if($obra[0]->comentarios != null)
            $obra[0]->comentarios = explode(";", $obra[0]->comentarios);   
        return view( 'obras/obra_show', compact('obra'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::check())
        {
            $obra = Obra::findOrFail($id);
            return view('obras/e_obra', compact('obra'));
        }

        return redirect('/login');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
            $obraModificar = Obra::findOrFail($id);
            $obraModificar->update($request->all());

            if($request->has('img'))
            {
                foreach($request->img as $foto)
                {
                    Foto::create(['obra_id'=>$id, 'ruta'=>$foto->store('public/img')]);
                }
            }

            if($request->has('fich'))
            {
                foreach($request->fich as $fichero)
                {
                    Fichero::create(['obra_id'=>$id,'nombre'=>pathinfo($fichero->getClientOriginalName(), PATHINFO_FILENAME), 'ruta'=>$fichero->store('public/ficheros')]);
                }
            }

            return redirect()->route('obras.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::check())
        {
            $obraBorrar = Obra::findOrFail($id);
            $ficherosDestruir = Obra::with('foto', 'fichero')->where('id', $id)->get();

            foreach($ficherosDestruir[0]->foto as $fotos)
            {
                Storage::delete($fotos->ruta);
                $fotos->delete();
            }

            foreach($ficherosDestruir[0]->fichero as $ficheros)
            {
                Storage::delete($ficheros->ruta);
                $ficheros->delete();
            }

            $obraBorrar->delete();

            return redirect()->route('home');
        }

        return redirect('/login');
    }

    public function search()
    {
        return view('obras/obra_consult');
    }

    public function quickSearch(Request $request)
    {
        $obra = new Obra;
        $consulta = $obra->newQuery();
        $consulta->where('titulo', 'like' , '%'.$request->input('titulo').'%');
        $resultado = $consulta->get();
        return view('obras/obra_consult_result', compact('resultado'));
    }

    public function filter(Request $request)
    {
        //Creamos la nueva consulta sobre la base de datos
        $obra = new Obra;
        $consulta = $obra->newQuery();

        if($request == null)
        {
            $resultado = $consulta->get()->all();
        }
        else
        {
            if(!is_null($request->input('titulo')))
            {
                $consulta->where('titulo', 'like' , '%'.$request->input('titulo').'%');
            }
            
            if(!is_null($request->input('autoria')))
            {
                $consulta->where('autoria', 'like' , '%'.$request->input('autoria').'%');
            }
            
            if(!is_null($request->input('genero_dramatico')))
            {
                $consulta->where('genero_dramatico', 'like' , '%'.$request->input('genero_dramatico').'%');
            }

            if(!is_null($request->input('traduccion')))
            {
                $consulta->where('traduccion', 'like' , '%'.$request->input('traduccion').'%');
            }

            if(!is_null($request->input('adaptacion')))
            {
                $consulta->where('adaptacion', 'like' , '%'.$request->input('adaptacion').'%');
            }

            if(!is_null($request->input('direccion')))
            {
                $consulta->where('direccion', 'like' , '%'.$request->input('direccion').'%');
            }

            if(!is_null($request->input('reparto')))
            {
                $consulta->where('reparto', 'like' , '%'.$request->input('reparto').'%');
            }

            if(!is_null($request->input('escenografia')))
            {
                $consulta->where('escenografia', 'like' , '%'.$request->input('escenografia').'%');
            }

            if(!is_null($request->input('figurines')))
            {
                $consulta->where('figurines', 'like' , '%'.$request->input('figurines').'%');
            }

            if(!is_null($request->input('sonido_y_musica')))
            {
                $consulta->where('sonido_y_musica', 'like' , '%'.$request->input('sonido_y_musica').'%');
            }

            if(!is_null($request->input('coreografia')))
            {
                $consulta->where('coreografia', 'like' , '%'.$request->input('coreografia').'%');
            }

            if(!is_null($request->input('figurines')))
            {
                $consulta->where('figurines', 'like' , '%'.$request->input('figurines').'%');
            }

            if(!is_null($request->input('sonido_y_musica')))
            {
                $consulta->where('sonido_y_musica', 'like' , '%'.$request->input('sonido_y_musica').'%');
            }

            if(!is_null($request->input('coreografia')))
            {
                $consulta->where('coreografia', 'like' , '%'.$request->input('coreografia').'%');
            }

            if(!is_null($request->input('resenyas_criticas')))
            {
                $consulta->where('material_grafico', 'like' , '%'.$request->input('material_grafico').'%');
            }

            if(!is_null($request->input('fecha_de_estreno')))
            {
                $consulta->where('fecha_de_estreno', $request->input('fecha_de_estreno'));
            }

            $resultado = $consulta->get();
        }

        return view('obras/obra_consult_result', compact('resultado'));
    }
}

resources/views/obras/c_obra.blade.php
@extends('layout_def')

@section('contenido')

<!-- Form contact -->
<br>
<div class="container">
<form method="POST" action="{{route('obras.store')}}" enctype="multipart/form-data">
 {!! csrf_field() !!}
    <p class="h2 text-center mb-4">Introduzca los datos de la obra</p>

    <div class="md-form">
    	<label>Título de la obra</label>
        <input type="text" name="titulo" maxlength="250" class="form-control">
    </div>
	<br>
    <div class="md-form">
    	<label>Autor de la obra</label>
        <input type="text" name="autoria" maxlength="250" class="form-control">
    </div>
	<br>
    <div class="md-form">
    	<label>Género dramático</label>
        <input type="text" name="genero_dramatico" maxlength="250" class="form-control">
    </div>
    <br>
    <div class="md-form">
    	<label>Traducción</label>
        <input type="text" name="traduccion" maxlength="250" class="form-control">
    </div>
    <br>
    <div class="md-form">
    	<label>Adaptacion</label>
        <input type="text" name="adaptacion" maxlength="250" class="form-control">
    </div>
	
	<br>
    <div class="md-form">
    	<label>Dirección</label>
        <textarea rows="4" type="text" name="direccion" class="form-control"></textarea>
    </div>
	<br>
    <div class="md-form">
    	<label>Reparto</label>
        <textarea rows="13" type="text" name="reparto" class="form-control"></textarea>
    </div>
    <br>
    <div class="md-form">
    	<label>Escenografía</label>
        <textarea rows="5" type="text" name="escenografia" class="form-control"></textarea>
    </div>
    <br>
    <div class="md-form">
        <label>Figurines</label>
        <textarea rows="5" type="text" name="figurines" class="form-control"></textarea>
    </div>
    <br>
    <div class="md-form">
        <label>Sonido y Música</label>
        <textarea rows="5" type="text" name="sonido_y_musica" class="form-control"></textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Coreografía</label>
        <textarea rows="5" type="text" name="coreografia" class="form-control"></textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Otros</label>
        <textarea rows="5" type="text" name="otros" class="form-control"></textarea>
    </div>
    <br>
    <div class="md-form">
        <label>Fecha de estreno</label>
        <input rows="5" type="date" name="fecha_de_estreno" class="form-control"></textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Reseñas críticas</label>
        <textarea rows="5" type="text" name="resenyas_criticas" class="form-control"></textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Bibliografía</label>
        <textarea rows="5" type="text" name="bibliografia" class="form-control"></textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Material Gráfico</label>
        <textarea rows="5" type="text" name="material_grafico" class="form-control"></textarea>
    </div>
    <br>
    <div class="md-form">
        <label>Comentarios</label>
        <textarea rows="5" type="text" name="comentarios" class="form-control"></textarea>
        <input type="hidden" name="usr_creador" value={{Auth::user()->name}}>
        <input type="hidden" name="usr_last_mod" value={{Auth::user()->name}}>
    </div>
    <br>
    <div class="md-form">
        <label>Subir imagen</label>
        <input type="file" name="img[]" multiple>
    </div>
    <br>
    <div class="md-form">
        <label>Subir ficheros relacionados</label>
        <input type="file" name="fich[]" multiple>
    </div>
    <br>
        <div class="text-center">
        <button class="btn btn-primary">INTRODUCIR<i class="fa fa-paper-plane-o ml-1"></i></button>
    <br>
    <br>
    
    </div>
</form>
<!-- Form contact -->
            

@stop

resources/views/obras/e_obra.blade.php
@extends('layout_def')

@section('contenido')

<!-- Form contact -->
<br>
<div class="container">
<form method="POST" action="{{route('obras.update', $obra->id)}}" enctype="multipart/form-data">
 {!! csrf_field() !!}
 {!!method_field('PUT')!!}
    <p class="h2 text-center mb-4">Modifique los datos de la obra que considere necesarios</p>

    <div class="md-form">
    	<label>Título de la obra</label>
        <input type="text" name="titulo" class="form-control" maxlength="250" value="{{$obra->titulo}}">
    </div>
	<br>
    <div class="md-form">
    	<label>Autor de la obra</label>
        <input type="text" name="autoria" class="form-control" maxlength="250" value="{{$obra->autoria}}">
    </div>
	<br>
    <div class="md-form">
    	<label>Género dramático</label>
        <input type="text" name="genero_dramatico" class="form-control" maxlength="250" value="{{$obra->genero_dramatico}}">
    </div>
	<br>
    <div class="md-form">
    	<label>Traducción</label>
        <input type="text" name="traduccion" class="form-control" maxlength="250" value="{{$obra->traduccion}}">
    </div>
    <br>
    <div class="md-form">
    	<label>Adaptacion</label>
        <input type="text" name="adaptacion" class="form-control" maxlength="250" value="{{$obra->adaptacion}}">
    </div>
	<br>
    <div class="md-form">
    	<label>Dirección</label>
        <textarea rows="4" type="text" name="direccion" class="form-control">{{$obra->direccion}}</textarea>
    </div>
	<br>
    <div class="md-form">
    	<label>Reparto</label>
        <textarea rows="13" type="text" name="reparto" class="form-control">{{$obra->reparto}}</textarea>
    </div>
    <br>
    <div class="md-form">
    	<label>Escenografía</label>
        <textarea rows="5" type="text" name="escenografia" class="form-control">{{$obra->escenografia}}</textarea>
    </div>
    <br>
    <div class="md-form">
        <label>Figurines</label>
        <textarea rows="5" type="text" name="figurines" class="form-control">{{$obra->figurines}}</textarea>
    </div>
    <br>
    <div class="md-form">
        <label>Sonido y Música</label>
        <textarea rows="5" type="text" name="sonido_y_musica" class="form-control">{{$obra->sonido_y_musica}}</textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Coreografía</label>
        <textarea rows="5" type="text" name="coreografia" class="form-control">{{$obra->coreografia}}</textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Otros</label>
        <textarea rows="5" type="text" name="otros" class="form-control">{{$obra->otros}}</textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Fecha de estreno</label>
        <input rows="5" type="date" name="fecha_de_estreno" class="form-control" value="{{$obra->fecha_de_estreno}}"></textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Reseñas críticas</label>
        <textarea rows="5" type="text" name="resenyas_criticas" class="form-control">{{$obra->resenyas_criticas}}</textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Bibliografía</label>
        <textarea rows="5" type="text" name="bibliografia" class="form-control">{{$obra->bibliografia}}</textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Material Gráfico</label>
        <textarea rows="5" type="text" name="material_grafico" class="form-control">{{$obra->material_grafico}}</textarea>
    </div>
    <br>
    <div class="md-form">
        <label>Comentarios</label>
        <textarea rows="5" type="text" name="comentarios" class="form-control">{{$obra->comentarios}}</textarea>
        <input type="hidden" name="usr_creador" value={{$obra->usr_creador}}>
         <input type="hidden" name="usr_last_mod" value={{Auth::user()->name}}>
    </div>
    <div class="md-form">
        <label>Añadir más imágenes</label>
        <input type="file" name="img[]" multiple>
    </div>
    <br>
    <div class="md-form">
        <label>Añadir más ficheros</label>
        <input type="file" name="fich[]" multiple>
    </div>
    <br>
        <div class="text-center">
        <button class="btn btn-primary">Modificar<i class="fa fa-paper-plane-o ml-1"></i></button>
    <br>
    <br>

    </div>
</form>
<!-- Form contact -->
            

@stop

resources/views/obras/obra_consult.blade.php
@extends('layout_def')

@section('contenido')

<!-- Form contact -->
<br>
<div class="container">
<form method="GET" action="{{route('obras.filter')}}">
 {!! csrf_field() !!}
    <p class="h2 text-center mb-4">Realice una consulta en la base de datos</p>

    <div class="md-form">
    	<label>Título de la obra</label>
        <input type="text" name="titulo" class="form-control">
    </div>
	<br>
    <div class="md-form">
    	<label>Autor de la obra</label>
        <input type="text" name="autoria" class="form-control">
    </div>
	<br>
    <div class="md-form">
    	<label>Género dramático</label>
        <input type="text" name="genero_dramatico" class="form-control">
    </div>
    <br>
    <div class="md-form">
    	<label>Traducción</label>
        <input type="text" name="traduccion" class="form-control">
    </div>
    <br>
    <div class="md-form">
    	<label>Adaptacion</label>
        <input type="text" name="adaptacion" class="form-control">
    </div>
	
	<br>
    <div class="md-form">
    	<label>Dirección</label>
        <textarea rows="4" type="text" name="direccion" class="form-control"></textarea>
    </div>
	<br>
    <div class="md-form">
    	<label>Reparto</label>
        <textarea rows="13" type="text" name="reparto" class="form-control"></textarea>
    </div>
    <br>
    <div class="md-form">
    	<label>Escenografía</label>
        <textarea rows="5" type="text" name="escenografia" class="form-control"></textarea>
    </div>
    <br>
    <div class="md-form">
        <label>Figurines</label>
        <textarea rows="5" type="text" name="figurines" class="form-control"></textarea>
    </div>
    <br>
    <div class="md-form">
        <label>Sonido y Música</label>
        <textarea rows="5" type="text" name="sonido_y_musica" class="form-control"></textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Coreografía</label>
        <textarea rows="5" type="text" name="coreografia" class="form-control"></textarea>
    </div>
    <br>
    <div class="md-form">
        <label>Fecha de estreno</label>
        <input rows="5" type="date" name="fecha_de_estreno" class="form-control"></textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Reseñas críticas</label>
        <textarea rows="5" type="text" name="resenyas_criticas" class="form-control"></textarea>
    </div>
    <br>
     <div class="md-form">
        <label>Material Gráfico</label>
        <textarea rows="5" type="text" name="material_grafico" class="form-control"></textarea>
    </div>
    <br>
        <div class="text-center">
        <button class="btn btn-primary">BUSCAR<i class="fa fa-paper-plane-o ml-1"></i></button>
    <br>
    <br>

    </div>
</form>
<!-- Form contact -->
            

@stop

resources/views/obras/obra_consult_result.blade.php
@extends('layout_def')

@section('contenido')

<div class="container" style="margin: 1em 3em 0 3em;">
<h2>Consulta</h2>
<br>
<div class="col-md-6">
	<form class="navbar-form navbar-left" role="search" action="{{route('obras.quicksearch')}}" method="GET">
		<div class="form-group">
			<div class="row">
				<div class="col-md-6" style="padding: 0">
					<input type="text" name="titulo" class="form-control" placeholder="Búsqueda rápida">
				</div>
				<div class="col-md-4" style="padding: 0">
				<input type="submit" class="btn btn-default" value="Buscar">
				</div>
			</div>
		</div>
	</form>
</div>
<div class="col-md-4" style="padding: 0">
	<a href={{route('search')}} class="btn btn-primary"> Búsqueda avanzada</a>
</div>
<br>
<br>
<h2>Resultados:</h2>
<br>
<div class="row">
	@foreach($resultado as $valor)
		<div class="card col-lg-5" style="margin: .5em; padding: 0;">
			<div class="card-header">
				<h3>{{$valor->titulo}}</h3>
			</div>
			<div class="card-body">
				<ul>
					<li>
						Autor: {{$valor->autoria}}
					</li>
					<li>
						Creado por: {{$valor->usr_creador}}
					</li>
				</ul>
			</div>
			<div class="card-footer">
				<a class="btn btn-primary" href="{{route('obras.show', $valor->id)}}">Ver ficha completa</a>
			</div>
		</div>
	@endforeach
</div>
</div>

@stop

resources/views/obras/obra_show.blade.php
@extends('layout_def')

@section('contenido')

<div class="container">
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">{{$obra[0]->titulo}}</h1>
    @if ($obra[0]->usr_creador == $obra[0]->usr_last_mod)
    	<p class="lead">Ficha realizada por: {{$obra[0]->usr_creador}}</p>
    @else
    	<p class="lead">Ficha realizada por: {{$obra[0]->usr_creador}}</p>
    	<p class="lead">Última modificación: {{$obra[0]->usr_last_mod}}</p>
    @endif
	
	<br>
	@if(Auth::check())
	<div class="row">
		<div class="col-md-3">
	    <a class="btn btn-primary" href="{{route('obras.edit', $obra[0]->id)}}">Editar entrada</a>
	    </div>
	    <div class="col-md-3">
		<form action="{{route('obras.destroy', $obra[0]->id)}}" method="POST">
			{!! csrf_field() !!}
	 		{!!method_field('DELETE')!!}
			<input type="submit" class="btn btn-danger" value="Borrar entrada">
		</form>
		</div>
	</div>
	@endif
  </div>
</div>
	
<div class="container">
	<div class="row">
		<div class="col-md-6">
			@if($obra[0]->autoria != null)
				<h3>Autor:</h3> <p class="lead">{{$obra[0]->autoria}}</p>
			@endif
			@if($obra[0]->genero_dramatico != null)
				<h3>Género dramático:</h3> <p class="lead">{{$obra[0]->genero_dramatico}}</p>
			@endif
			@if($obra[0]->traduccion != null)
				<h3>Traducción: </h3>  <p class="lead">{{$obra[0]->traduccion}}</p>
			@endif
			@if($obra[0]->adaptacion != null)
				<h3 >Adaptación: </h3> <p class="lead">{{$obra[0]->adaptacion}}</p>
			@endif
			@if($obra[0]->direccion != null)
				<h3 >Dirección: </h3>
				@foreach($obra[0]->direccion as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif
			@if($obra[0]->reparto != null)
				<h3>Reparto:</h3>
				@foreach($obra[0]->reparto as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif
			@if($obra[0]->escenografia != null)
			<h3>Escenografía: </h3>
				@foreach($obra[0]->escenografia as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif

			@if($obra[0]->figurines != null)
				<h3 >Figurines: </h3>
				@foreach($obra[0]->figurines as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif

			@if($obra[0]->sonido_y_musica != null)
				<h3 >Sonido y Música: </h3>
				@foreach($obra[0]->sonido_y_musica as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif
		</div>
		<div class="col-md-6">
			@if($obra[0]->coreografia != null)
				<h3 >Coreografía: </h3>
				@foreach($obra[0]->coreografia as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif
			@if($obra[0]->otros != null)
				<h3 >Otros: </h3>
				@foreach($obra[0]->otros as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif
			@if($obra[0]->fecha_de_estreno != null)
				<h3>Fecha de estreno:</h3>
				<p class="lead">{{$obra[0]->fecha_de_estreno}}</p>
			@endif
			@if($obra[0]->resenyas_criticas != null)
				<h3 >Reseñas Críticas: </h3>
				@foreach($obra[0]->resenyas_criticas as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif
			@if($obra[0]->bibliografia != null)
				<h3 >Bibliografía: </h3>
				@foreach($obra[0]->bibliografia as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif
			@if($obra[0]->material_grafico != null)
				<h3 >Material gráfico: </h3>
				@foreach($obra[0]->material_grafico as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif
			@if($obra[0]->comentarios != null)
				<h3 >Comentarios: </h3>
				@foreach($obra[0]->comentarios as $valor)
					<p class="lead">{{$valor}}</p>
				@endforeach
			@endif
		</div>
	</div>
	
	<div style="padding-bottom: .5em">
		@if(!$obra[0]->foto->isempty())
			<h3>Imágenes: </h3>
			<div class="row">
				@foreach($obra[0]->foto as $img)
					<div class="col-md-6">
						<a href="{{Storage::url($img->ruta)}}">
			  				<img class="img-responsive" src="../{{Storage::url($img->ruta)}}" alt="" style="width:100%; max-height: 400px;">
			  			</a>
					</div>
				@endforeach
			</div>
		@endif
	</div>

	<div style="padding-bottom: .5em">
		@if(!$obra[0]->fichero->isempty())
			<h3>Ficheros relacionados</h3>
			<ul class="list-group">
	  			@foreach($obra[0]->fichero as $fichero)
					<li class="list-group-item">
						<div class="col-md-10">
							{{$fichero->nombre . ".pdf"}}
						</div>
						<div class="col-md-2"> 
							<a class="btn btn-primary" href="{{Storage::url($fichero->ruta)}}" style="width:100%;">Ver</a>
						</div>
					</li>
				@endforeach
			</ul>
		@endif
	</div>

</div>
</div>

@stop