routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('creausuario', function(){

	$usuario = new App\User;
	$usuario->name = "Administrador";
	$usuario->email = "administrador@correocorrecto.com";
	$usuario->password = bcrypt('admin');
	$usuario->save();

	return $usuario;

});

Route::resource('obras', 'ObrasController');

Route::get('/', ['as' => 'home', 'uses' => 'PagesController@home']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('obra/search', ['as' => 'search', 'uses' => 'ObrasController@search']);

Route::get('obra/filter', ['as' => 'obras.filter', 'uses' => 'ObrasController@filter']);

Route::get('galeria/index', ['as' => 'galeria.index', 'uses' => 'ImagenesController@index']);

Route::get('obra/quick', ['as' => 'obras.quicksearch', 'uses' => 'ObrasController@quickSearch']);

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

resources/views/galeria/galeria.blade.php
@extends('layout_def')

@section('contenido')

<div class="row" style="padding: 3em;">
	@foreach($response as $img)
		<div class="col-md-4">
    		<div class="card">
  				<img class="card-img-top" src="{{Storage::url($img->ruta)}}" alt="" style="width:100%; max-height: 400px;">
  				<div class="card-footer">
  				<br>
  				<br>
    			<a href="{{route('obras.show', $img->obra_id)}}" class="btn btn-primary">Accede a la ficha</a>
  			</div>
		</div>
				
			</div>
	@endforeach
</div>
@stop